language: elixir
elixir:
  - 1.9
  - 1.10
otp_release:
  - 22.0
matrix:
  include:
    - elixir: '1.9'
      script:
        - mix format --check-formatted
        - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
