language: elixir
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 18.0
matrix:
  include:
    - elixir: '1.7'
      script:
        - mix format --check-formatted
        - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
